### ISSUE TITLE
Sprite Wormies

### ISSUE THREAD

**Issue by greenpicat** [dkrammer/back-alley-games#11]
**Description**: Little wormies (1-pixel tall lines) appear on top of Sara's sprite and possibly others as well. They seem to be the bottom of the sprite looping back to the top.
**Environment**: Vertical slice web deployment, etc.
**Steps to Reproduce**:
1. Travel to backroom or any area where sprite appears large on the screen
2. Face left, right, or up.

**Expected Behavior**: no wormies
**Actual Behavior**: wormies
**Priority**: like 3/5

**Comment by niwaniuk** [comment]
Fixed with new Sara sprite!
