### ISSUE TITLE
Have Sara pause before recognizing Memory Song

### ISSUE THREAD

**Issue by greenpicat** [dkrammer/back-alley-games#12]
Description: Right now, when Memory song plays, Sara comments on it very quickly. Zoe suggests having her pause a bit longer so it feels like she has a moment of recognition.

Priority: like 1/5

**Comment by niwaniuk** [comment]
I added another second (60 frames) to the wait, and I think it feels better now.

**Comment by niwaniuk** [comment]
I'm going to consider this closed, but it's very easy to adjust again if we decide to later.
