### ISSUE TITLE
Sara can stand inside the backroom shelves

### ISSUE THREAD

**Issue by greenpicat** [dkrammer/back-alley-games#14]
Description: Sara is able to stand in the shelves a little bit (see below). This may be fixable by adjusting the art, or else by adding collision to the shelves.

![image](https://user-images.githubusercontent.com/60548686/110889446-5ca0e980-82ab-11eb-8ba8-7dee4966ee53.png)

Priority: like 1.5/5 idk

**Comment by niwaniuk** [comment]
I messed around with this a little, but personally i feel like adding collision to these looks weird. Any chance you think you could just move these shelves up a few pixels, @greenpicat ?
(this is as high as you can move up when collision is added)
![Screenshot 2021-03-18 162837](https://user-images.githubusercontent.com/55297737/111705935-1269bc00-8807-11eb-8397-351e1b34993e.png)

**Comment by greenpicat** [comment]
> 
> 
> I messed around with this a little, but personally i feel like adding collision to these looks weird. Any chance you think you could just move these shelves up a few pixels, @greenpicat ?
> (this is as high as you can move up when collision is added)
> ![Screenshot 2021-03-18 162837](https://user-images.githubusercontent.com/55297737/111705935-1269bc00-8807-11eb-8397-351e1b34993e.png)

i was thinking using altimate movement to set the collider to be smaller? but yeah I can also just adjust the art. it will mean the boundary between the floor and the wall no longer falls along the rpgmaker grid line but that shouldn't hurt anything

**Comment by niwaniuk** [comment]
> > I messed around with this a little, but personally i feel like adding collision to these looks weird. Any chance you think you could just move these shelves up a few pixels, @greenpicat ?
> > (this is as high as you can move up when collision is added)
> > ![Screenshot 2021-03-18 162837](https://user-images.githubusercontent.com/55297737/111705935-1269bc00-8807-11eb-8397-351e1b34993e.png)
> 
> i was thinking using altimate movement to set the collider to be smaller? but yeah I can also just adjust the art. it will mean the boundary between the floor and the wall no longer falls along the rpgmaker grid line but that shouldn't hurt anything

Oh! I could do that instead if you'd prefer, it'd just require an event on the bottom line of the shelves. It's really up to you what you think is better!
