### ISSUE TITLE
Spamming the backroom exit puts the player in a collision box

### ISSUE THREAD

**Issue by greenpicat** [dkrammer/back-alley-games#17]
Description: If the player tries to leave the backroom area before collecting all items, they can force their way up and trigger it twice in a row, which also triggers the player to move down twice in a row, which puts them inside the cardboard box collision boxes. This sucks. The professor pointed out this can be fixed by having the player move to a hard-coded spot or by enabling the "if you cant move dont move" option
Version: blah blah blah all of them probably
Steps to reproduce:

1. Get to the backroom
2. Do not collect all items
3. Spam the exit

Expected behavior: Play can move around the backroom after trying to leave early
Actual behavior: Player gets stuck in the cardboard boxes
Priority: like 2/5 this is an actual bug

**Comment by niwaniuk** [comment]
I tried a bunch of times to get this to trigger after adding skip if cannot move, so it **should** be fixed.
