### ISSUE TITLE
Doors keep odd directions

### ISSUE THREAD

**Issue by AttacktoWin** [dkrammer/back-alley-games#48]
Description: I walked into Alex's Room (unfinished) while facing right and it retained my direction. Might be better to just set direction on the doors especially since we've got the fade to black transition and the sound effects.

Priority: 1/5 a neat tweak

**Comment by niwaniuk** [comment]
I'm pretty sure this is the only one I missed, and I think it's just because I kept the transition from when you guys originally made the maps xD this one will be fixed right away, but I'll keep an eye out for any others
